### ISSUE TITLE
2 problems 

### ISSUE THREAD

**Issue by markbucko12341** [Naikzer/HUD-GTAVRP#3]
1, I have the menu pop up to make a new player but when I click save in the console it says  outfit been saved but the menu don't go off

2 with the hunger thing I cant install the sql 
![image](https://user-images.githubusercontent.com/43683580/61215874-eb8ae680-a703-11e9-91ce-7c75b0ff478b.png)

**Comment by dolutattoo** [comment]
1 - Wait for an update of the script
2 - Check my PR

**Comment by markbucko12341** [comment]
what do you mean PR lol

**Comment by markbucko12341** [comment]
sorted lol CREATE TABLE `hungerthirst` (
  `idSteam` varchar(255) NOT NULL,
  `hunger` int(11) NOT NULL DEFAULT '100',
  `thirst` int(11) NOT NULL DEFAULT '100' (,)  <----   not ment to be here lol 
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by markbucko12341** [comment]
THANK YOU FOR YOUR AMAZING WORK DUDE  <3

**Comment by dolutattoo** [comment]
PR = Pull Request
